#!/bin/sh

# [How do you print in a Go test using the "testing" package? - Stack Overflow https://stackoverflow.com/questions/23205419/how-do-you-print-in-a-go-test-using-the-testing-package]
#
# The structs testing.T and testing.B both have a .Log and .Logf method
# The -v flag shows logs.

while getopts "o:" option; do
	case "${option}" in
	o)
		opts="$OPTARG"
		;;
	\?)
		exit 1
		;;
	esac
done

shift $(($OPTIND - 1))

dir="`dirname "$1"`"

cd "$dir"
shift

if [ -p /dev/stdin ]; then
	go test $opts . "$@" < /dev/stdin
else
	go test $opts . "$@"
fi
